version: '3.8'

services:
  mirror-server:
    build:
      context: .
      dockerfile: Containerfile
    container_name: mirror-server
    ports:
    - "8680:80"
    volumes:
    # Mount mirror directory - adjust path based on your setup
    # For default setup: ~/data/mirror
    # For NAS: /var/mnt/dpool/software/mirror
    # Set MIRROR_ROOT environment variable to override the default
    # - "${MIRROR_ROOT:-~/data/mirror}:/var/www/mirror:ro,z"
    - /var/mnt/dpool/software/mirror:/var/www/mirror:ro,z
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
    - mirror-network

networks:
  mirror-network:
    driver: bridge

volumes:
  mirror-data:
    external: false
