[Default]
LogLevel = Warning
SSL = True

[local-matrix]
Homeserver = https://matrix.notsuspicious.net
ListenAddress = 0.0.0.0
ListenPort = 8009
SSL = False
UseKeyring = False
IgnoreVerification = True
