pulse.rules = [
    {
        # Block Slack from changing microphone volume
        matches = [
            { application.process.binary = "slack" }
        ]
        actions = { quirks = [ block-source-volume ] }
    }
]
