#!/bin/sh

# XMonad build script with required packages
exec ghc --make xmonad.hs \
    -i \
    -ilib \
    -fforce-recomp \
    -main-is main \
    -v0 \
    -outputdir /var/home/zach/.cache/xmonad/build-x86_64-linux \
    -o /var/home/zach/.cache/xmonad/xmonad-x86_64-linux \
    -package unix \
    -package xmonad \
    -package xmonad-contrib \
    -package process \
    -package containers