[private]
_default:
    just --list


[private]
[no-cd]
c:
    #!/bin/bash 
    set -euo pipefail 

    qwik --choose


# Do a rebase for the current repo
[no-cd]
rebase count="2":
    #!/bin/bash 
    set -euo pipefail 
    
    git rebase -i "HEAD~{{count}}"


# Add commit and do rebase 
[no-cd]
add_and_rebase count="2":
    #!/bin/bash 
    set -euo pipefail 

    git add -A 
    git commit -m blah
    qwik rebase {{count}}


alias i := paste_image
# Paste image 
[no-cd]
paste_image name="image.png":
    #!/bin/bash 
    set -euo pipefail 

    wl-paste -t image/png > "{{name}}"


# Dump clipboard and ingest into second-brain inbox
[no-cd]
clip2brain:
    #!/bin/bash 
    set -euo pipefail 

    clip2brain

# Take a voice note, transcribe it, and dump to second-brain inbox
[no-cd]
clip2brain-audio:
    #!/bin/bash 
    set -euo pipefail 

    clip2brain --audio
